### PR TITLE
Tests now always run, and don't explode.

### PR DESCRIPTION
**Pull request by jasiek**
Tested against OpenSSL 1.1.0g.

### CODE REVIEW

**Comment by akryeem-INTC** [comment]
> Patch so that we can build against SDK v2.0.
This change means that SGXSSL will run only with SDK version >=2.0, breaking backward compatibility.
There is a variable available in the build script "SGXSDK_INT_VERSION" which may be used in order to determine which SGXSDK version we're using.

**Comment by jasiek** [comment]
I can change it to be compatible with earlier versions. What is the earliest you want me to aim for?

**Comment by akryeem-INTC** [comment]
SDK 1.7 is the earliest version that need to be supported.
This change depends only on SDK 2.0, I think checking that SDK version < 2.0 is enough and should be OK.

Thanks,
Alaa

**Comment by akryeem-INTC** [comment]
Changes fixed to support backward compatibility and committed.

**Pull request closed without merging**
